version: "3"
services:
  app:
    container_name: app
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - ./app:/app
      - /app/node_modules # do not try to map host modules against container
    ports:
      - 4200:4200
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /tmp
    ports:
      - 8000:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
