version: "3"
services:
  app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - 4200:4200
