spring:
  devtools.remote.secret: secret
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  output.ansi.enabled: ALWAYS
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
server:
  servlet:
    contextPath: "/api"
